### ISSUE TITLE
New publish does not have TXT record

### ISSUE THREAD

**Issue by dalepsmith** [keepsimple1/mdns-sd#72] opened 2022-11-11 01:10 UTC
If start browsing, existing services have TXT record info.

However, if I publish a service while browsing (say with avahi-publish-service), the TXT info is missing.

But if I publish BEFORE I start the browse, I do get the TXT info.

**Comment by keepsimple1** [comment] 2023-02-24 18:28
I was able to reproduce this issue, and here is a log: 

publisher:
```
$ avahi-publish-service pi1 _pub-test._udp 1234 path=one
Established under name 'pi1'
```

browser:
```
 cargo run --example query _pub-test._udp
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/query _pub-test._udp`
At 165.572µs : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 1.015156173s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 3.034112873s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 7.04311425s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 15.053982273s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 31.071824092s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
        At 63.074141451s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 127.190416462s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 255.205053949s : Received other event: SearchStarted("_pub-test._udp.local. on addrs [192.168.0.115]")
At 396.578404231s : Received other event: ServiceFound("_pub-test._udp.local.", "pi1._pub-test._udp.local.")
At 396.578439007s: Resolved a new service: pi1._pub-test._udp.local. IP: {192.168.0.114} TXT properties: TxtProperties { properties: [] }
```

**Comment by keepsimple1** [comment] 2023-02-24 22:46
Root cause analysis: 

In some publishing messages, TXT records are in front of PTR records.  However, our current implementation only inserts a new instance-to-resolve based on PTR records. This means that any records (including TXT records) processed before PTR would not be used to resolve an instance, effectively skipped.

**Comment by keepsimple1** [comment] 2023-02-25 00:36
My testing shows that the problem is fixed with the PR.

**Closed by keepsimple1** 2023-02-25 00:36 UTC
Labels: bug
